TECH-538-E2E-Test-SC-Deployment-from-(Non)-KYC-Verified-Addresses
chain4travel/caminojs pull request #36
Opened 2023-02-14 13:55 UTC by parousisv

E2E Smart Contract test cases regarding including:

- SC Deployment
- Admin, Gas Fee, KYC and Blacklist Role Check
- X -> C token exchange

Web3 library addition - necessary for SC testing. Changes in package.json and yark.lock files have been made in order to include web3 library.

2023-02-16 08:41 UTC, knikos requested changes

2023-02-16 08:41 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +describe("Admin-Role-Testing", (): void => {
I would add the Prefix "Camino-CChain-" just for keeping it as convention similar to anax's

2023-02-16 08:41 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +  const path = require("path")
`fs` and `path` do not seem to be used

2023-02-16 08:41 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +  const account = web3.eth.accounts.privateKeyToAccount("56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027")
extract private key also to a constant

2023-02-16 08:41 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +  web3 = new Web3("http://127.0.0.1:9650/ext/bc/C/rpc")
since you introduced [e2e_tests/camino/common/caminoConfig.json](https://github.com/chain4travel/caminojs/pull/36/files#diff-ee08d1e33b451ff0b97ae7a8f43f440e0a34a1d83985c9d8fe837092f42edc6d) use it to replace the hardcoded ip and port

2023-02-16 08:41 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +let ABI = []
can be converted into a const within the beforeAll scope

2023-02-16 08:41 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +let web3: any
can be converted into a const within the beforeAll scope

2023-03-08 14:31 UTC, knikos requested changes

2023-03-08 14:31 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +  const ABI = [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"addr","type":"address"},{"indexed":false,"internalType":"uint256","name":"role","type":"uint256"}],"name"
try reading the file instead of importing the whole ABI as string?

2023-03-08 14:31 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +      (x) => x.events.SetRole.returnValues.role,
comment `// "from" is the address where the tx comes from and "gas" is the gas limit` in unncessary

2023-03-08 14:31 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +describe("Camino-CChain-Gas-Fee-Role-Testing", (): void => {
i think the  suffix "-Testing" is superfluous and can be removed overall

2023-03-21 09:36 UTC, knikos commented on e2e_tests/e2etestlib.ts
> -    process.env.NETWORK_ID ? parseInt(process.env.NETWORK_ID) : 12345
why is this line removed?

2023-03-21 09:36 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +          .grantRole(gasFeeAddr, 2)
I would suggest to include all role constants in a separate file under /src/apis/evm (maybe camino_contstants.ts or something like that) and reference all roles in this test via static constants

2023-03-21 09:36 UTC, knikos commented on e2e_tests/camino/cchain_nomock.test.ts
> +      Matcher.toBe,
can this be replaced with a Matcher.toThrow?

2023-03-21 13:06 UTC, knikos approved these changes

2023-03-21 13:24 UTC, c4t-ag requested changes

2023-03-21 13:24 UTC, c4t-ag commented on package.json
> +    "web3": "^1.8.2",
I think dev_dependencies is the right place
Maybe look also for some of the others if they are at right place (stream-browserify ??)

2023-03-22 08:07 UTC, c4t-ag approved these changes
👍

2023-03-22 08:08 UTC, merged