Signavault API implementation and transaction example
chain4travel/caminojs pull request #53
Opened 2023-03-24 15:58 UTC by charalarg

## Description ##
This PR adds the implementation of the signavault API in order to be used from the wallet. The implementation consists of the following functions wrapping the corresponding signavault calls:  

- **createTx**: Creates the initial transaction and adds the sender's signature.
- **getTxs**: Fetches the pending transactions of the alias that sender belongs to.
- **signTx**: Adds sender's signature to an already existing pending transaction.
- **issueTx**: Issues a transaction to the network. This could be called by any member of the transaction's alias.   

In addition, this PR sets up an example simulating a multisig register node transaction composed and send through signavault.

## Changes ##

- Implementation of `Signavault` class handing the communication with the service.
- Implementation of `MultisigAPI`endpoints.
- Implementation of the `buildRegisterNodeTx-P-Chain-Msig-from-separate-signatures-signavault.ts` example.

2023-03-24 16:23 UTC, karafyllidis approved these changes

2023-03-27 11:32 UTC, DerTiedemann requested changes

2023-03-27 11:32 UTC, DerTiedemann commented on src/signavault/api.ts
> +  }
The only thing that changes here are the HTTP methods and the body object, which is generic. Is there a clean way to facor this into a utility call?

2023-03-27 11:32 UTC, DerTiedemann commented on src/signavault/index.ts
> +    this.url = url
Why are we handcrafting this logic, there is a standart type for URLs:
https://developer.mozilla.org/en-US/docs/Web/API/URL

2023-03-27 11:32 UTC, DerTiedemann commented on src/signavault/api.ts
> +}
Not sure if relevant, but should those type have appropriate names with a signavault prefix, so you can know they are not the default type offered by the library

2023-03-27 11:32 UTC, DerTiedemann commented on src/signavault/api.ts
> +    }
Whats happening here and why do we need a DB for it?

2023-03-28 15:10 UTC, charalarg commented
Closed as we moved both the example and the signavaultjs client to signavault repo.

2023-03-28 15:10 UTC, closed without merging