[PVM] MultisigAliasTx implementation
chain4travel/caminojs pull request #75
Opened 2023-05-25 11:09 UTC by charalarg

## Description ##
This PR adds the MultisigAliasTx implementation on the js library in order to be able to be used from the camino-suite. The equivalent implementation of the MultisigAliasTx on the node is described in this [PR](https://github.com/chain4travel/caminogo/pull/246) 

## Changes ##
- Implementation of the MultisigAliasTx Class that handles the tx logic.
- Implementation of the MultisigAlias Class which represents the alias definition in the tx.
- Added api and builder functions.
- Added unit tests.
- Added examples for both creating a new multisig alias definition (single sig tx) and updating an already existing ones (multisig tx).

2023-05-29 13:23 UTC, knikos requested changes

2023-05-29 13:23 UTC, knikos commented on tests/apis/platformvm/multisigaliastx.test.ts
> +  undefined
these 2 last parameters can be omitted

2023-05-29 13:23 UTC, knikos commented on tests/apis/platformvm/multisigaliastx.test.ts
> +        )
` new SECPOwnerOutput(
          outputOwners.getAddresses(),
          outputOwners.getLocktime(),
          outputOwners.getThreshold()
        )`
could be replaced by
`new ParseableOutput(outputOwners),`

2023-05-29 13:23 UTC, knikos commented on tests/apis/platformvm/multisigaliastx.test.ts
> +  })
could you add a unit test maybe for `getMultisigAlias` or do you think it doesn't make sense?

2023-05-29 13:23 UTC, knikos commented on src/apis/platformvm/multisigaliastx.ts
> +  }
unused setters and getters can be completely removed and added if and when needed

2023-05-29 13:23 UTC, knikos commented on examples/common/examplesConfig.json
> +  "networkID": 1002
i would recommend a new json called `examplesCaminoConfig.json` to be created and referenced. and this change to be reverted

2023-05-29 13:23 UTC, knikos commented on src/apis/platformvm/api.ts
> +   * @param multisigAliasParams An object containing the parameters for the multisigAliasTx
maybe reorder parameters to match the function's signature

2023-05-30 07:55 UTC, knikos approved these changes

2023-05-30 08:34 UTC, c4t-ag requested changes

2023-05-30 08:34 UTC, c4t-ag commented on examples/common/examplesConfig.json
> -  "networkID": 12345
Pls. revert

2023-05-30 08:34 UTC, c4t-ag commented on examples/common/examplesKopernikusConfig.json
> +{
Pls. revert

2023-05-30 09:02 UTC, c4t-ag approved these changes

2023-05-30 09:03 UTC, merged