DAC: General Proposal
chain4travel/caminojs pull request #98
Opened 2024-08-22 17:06 UTC by VjeraTurk

2024-08-23 15:46 UTC, VjeraTurk commented
@evlekht I noticed that there are no examples for AddVote for BaseFee and GeneralProposal. Should I add those to make sure there's a way to test the functionality within the caminojs itself.

2024-08-26 08:43 UTC, VjeraTurk commented on jest.config.js
@mo-c4t took a look and approved the change

2024-08-26 09:49 UTC, evlekht commented
> @evlekht I noticed that there are no examples for AddVote for BaseFee and GeneralProposal. Should I add those to make sure there's a way to test the functionality within the caminojs itself.

add them later, I'd suggest to create tech-debt issue for this

2024-08-26 18:11 UTC, evlekht requested changes

2024-08-26 18:11 UTC, evlekht commented on tests/apis/avm/api.test.ts
> +      adapter: undefined,
are those changes intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/avm/api.test.ts
> +      //data: '{"id":10,"method":"avm.getBalance","params":{"address":"X-local1d6kkj0qh4wcmus3tk59npwt3rluc6en77ajgr4","assetID":"ATH","includePartial":true},"jsonrpc":"2.0"}',
are those changes intended?

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addVoteTx.ts
> +  const proposal = new GeneralProposal()
is it used?

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addGeneralProposalTx.ts
naming is misleading
we don't have addGeneralProposalTx, we have addProposalTx which has proposal field, and this field's value might be generalProposal.

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addVoteTx.ts
> +      vote.getProposalID().toString(),
this looks confusing, imo. This example is about creating addVoteTx with pchain, right? Then why do you first create addVoteTx empty object manually and then use default empty proposal id from it as argument in func that will create real addVoteTx?
Either create real proposal first or just use some random id. But keep in mind, that without real proposal, addVoteTx will always fail.

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addVoteTx.ts
> +      1, // how to find this?
Proposal will contain array of options. Voter must know which option he wants to vote on.

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addVoteTx.ts
> +//TODO: @VjeraTurk add missing example for adding vote to General and Base Fee Proposal
All votes will look the same regardless of proposal type.

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addGeneralProposalTx.ts
> +    1,
Since its example, I would suggest to replace threshold nominator args values (1 and 2) with something more relevant. (See denominator value in caminogo)

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addGeneralProposalTx.ts
> +    "THIS STRING IS 256 CHARACTERS xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
I'd suggest to replace text with something like "option 1 content", same for other options

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addGeneralProposalTx.ts
> +  const txs = await pchain.getUTXOs(pAddressStrings)
why name it txs? type is getUTXOsResponse or something like this. It has nothing to do with transactions

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addVoteTx.ts
> +  const txs = await pchain.getUTXOs(pAddressStrings)
why name it txs? type is getUTXOsResponse or something like this. It has nothing to do with transactions

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addGeneralProposalTx.ts
> +      new Buffer([1, 2, 3, 4]), // description
I'd suggest to add "some proposal description" buffer here instead of 12345 buffer

2024-08-26 18:11 UTC, evlekht commented on examples/platformvm/addAddMemberProposalTx.ts
> +  const txs = await pchain.getUTXOs(pAddressStrings)
why name it txs? type is getUTXOsResponse or something like this. It has nothing to do with transactions

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
plz, name it with something more human-readable ^^' I don't see a reason to shrink it like this here

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +  //Example issued by Playground:
what is this comment for?
Also, I would avoid referencing cli playground, because its just one specific tool to create tx, it could be any other tool as well

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +      //"P-kopernikus18jma8ppw3nhx5r4ap8clazz0dps7rv5uuvjh68"
is this intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
same naming

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +      //assetID:
is this intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +      //  "59eb48b8b3a928ca9d6b90a0f3492ab47ebf06e9edc553cfb6bcd2d3f38e319a",
is this intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +        //.typeToBuffer(bintools.cb58Encode(Buffer.from(20)), "cb58")
is this intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +          /*ids: {
is this intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +
I think that empty line is not needed

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +          //txid: "2202d10a4489024915422013a0d048b06ee7bda83e4777bc89c55f042d7a5842"
is this intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +                //bytes: "3cb7d3842e8cee6a0ebd09f1fe884f6861e1b29c"
is this intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +        //new Buffer([1, 2, 3, 4]),
is this intended?

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
naming

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
naming

2024-08-26 18:11 UTC, evlekht commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
naming

2024-08-27 09:15 UTC, VjeraTurk commented on tests/apis/avm/api.test.ts
> +      //data: '{"id":10,"method":"avm.getBalance","params":{"address":"X-local1d6kkj0qh4wcmus3tk59npwt3rluc6en77ajgr4","assetID":"ATH","includePartial":true},"jsonrpc":"2.0"}',
The problem is when just this single test is called,
 it requires the adapter and the data id (number of calls) is 1
 
 
![image](https://github.com/user-attachments/assets/30c29a36-7159-4080-ad77-cfbf53e1b3eb)

2024-08-27 09:18 UTC, VjeraTurk commented on tests/apis/avm/api.test.ts
> +      adapter: undefined,
The problem is when just this single test is called,
 it requires the adapter and the data id (number of calls) is 1
 
 
![image](https://github.com/user-attachments/assets/30c29a36-7159-4080-ad77-cfbf53e1b3eb)

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addGeneralProposalTx.ts
I changed all the names to format e.g. : **addProposalTx.** generalProposal.ts
This will keep the addProposalTx tests together but not in a separate file :+1:

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addGeneralProposalTx.ts
AddProposalTx and addVoteTx extend the BaseTx

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addVoteTx.ts
> +  const proposal = new GeneralProposal()
No, the example contains "TODO:" for it to be created later.
The main function is not called so running the example file doesn't fail.

This file is just a Draft for a future example.

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addVoteTx.ts
> +      vote.getProposalID().toString(),
Sorry for the confusion. 

The example contains "TODO:" for it to be created later.
The main function is not called so running the example file doesn't fail.

**This file is just a Draft for a future example.**

We have agreed so here: https://github.com/chain4travel/caminojs/pull/98#issuecomment-2309807094


In future, I want to make it a standard that **examples and tests match** - that is: jest and ts-node tests **work on the same examples.**  In this case, yes, the vote will be added to a General Proposal created by the same test. 
 
Achraf used to use transaction HEX's created by front end, and I want always to use the ones created by examples.

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addVoteTx.ts
> +      1, // how to find this?
The confusion came from AdminProposal having _optionIndex field. 
https://github.com/chain4travel/caminojs/blob/fbc7ea9610c2f798dc708b8d2684c48dca69173b/src/apis/platformvm/addproposaltx/adminproposal.ts#L15

I don't fully understand why the index is needed here and if GeneralProposal would benefit from having it. 

It's just a general thought how to ensure the **option index matches the vote option** (not to leave space for a mistake in frontend - connecting the wrong index to a vote option).

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addVoteTx.ts
> +//TODO: @VjeraTurk add missing example for adding vote to General and Base Fee Proposal
So having AddVote tests for 2 different proposal types is very much redundant? 
I will only add the one for GeneralProposal then, in future.

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addGeneralProposalTx.ts
> +    "THIS STRING IS 256 CHARACTERS xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
It's meant to demonstrate how long the option can be

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addGeneralProposalTx.ts
> +  const txs = await pchain.getUTXOs(pAddressStrings)
I changed all the names to format e.g. : **addProposalTx.** generalProposal.ts
This will keep the addProposalTx tests together but not in a separate file

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addVoteTx.ts
> +  const txs = await pchain.getUTXOs(pAddressStrings)
renamed

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addAddMemberProposalTx.ts
> +  const txs = await pchain.getUTXOs(pAddressStrings)
renamed

2024-08-28 12:27 UTC, VjeraTurk commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
Renamed

2024-08-28 12:27 UTC, VjeraTurk commented on tests/apis/platformvm/addproposaltx.test.ts
> +  //Example issued by Playground:
Ok, I removed all the unnecessary comments.

( In future, want all the example HEXs to be generated by the caminojs examples - not by suite or cli playground. I want to replace the existing ones.)

2024-08-28 12:27 UTC, VjeraTurk commented on examples/platformvm/addGeneralProposalTx.ts
Test if this goes pending by default

2024-08-28 12:39 UTC, evlekht commented on examples/platformvm/addGeneralProposalTx.ts
> +    "THIS STRING IS 256 CHARACTERS xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
maybe lets make one option with text like "option with max len 256 characters xxxxxx...xxx"

2024-08-29 12:22 UTC, VjeraTurk commented on tests/apis/avm/api.test.ts
> +      adapter: undefined,
addressed by adding a comment
 // uncomment if just this single test is run

2024-08-29 12:22 UTC, VjeraTurk commented on tests/apis/avm/api.test.ts
> +      //data: '{"id":10,"method":"avm.getBalance","params":{"address":"X-local1d6kkj0qh4wcmus3tk59npwt3rluc6en77ajgr4","assetID":"ATH","includePartial":true},"jsonrpc":"2.0"}',
addressed by adding a comment
 // uncomment if just this single test is run

2024-08-29 12:24 UTC, VjeraTurk commented on tests/apis/platformvm/addproposaltx.test.ts
> +        //new Buffer([1, 2, 3, 4]),
removed

2024-08-29 12:26 UTC, VjeraTurk commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
renamed to addProposalTransaction

2024-08-29 12:27 UTC, VjeraTurk commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
renamed to addProposalTransaction

2024-08-29 12:27 UTC, VjeraTurk commented on tests/apis/platformvm/addproposaltx.test.ts
> +    const apTx: AddProposalTx = new AddProposalTx()
renamed to addProposalTransaction

2024-08-29 12:31 UTC, VjeraTurk commented on tests/apis/platformvm/addproposaltx.test.ts
> +                //bytes: "3cb7d3842e8cee6a0ebd09f1fe884f6861e1b29c"
removed

2024-08-30 01:26 UTC, evlekht approved these changes

2024-09-01 19:31 UTC, merged